version: 2.1

executors:
  tox:
    docker:
      - image: themattrix/tox
    working_directory: ~/repo

commands:
  tox:
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run: tox -e << parameters.env >>

jobs:

  lint:
    executor: tox
    steps:
      - tox: {env: "lint"}

  test:
    executor: tox
    steps:
      - tox: {env: "test,upload-coverage"}

  examples:
    executor: tox
    steps:
      - tox: {env: "examples"}

  mypy:
    executor: tox
    steps:
      - tox: {env: "mypy"}

  license:
    executor: tox
    steps:
      - tox: {env: "license"}

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test
      - examples
      - mypy
      - license
